- name: playbook_zdls_200
  hosts: zdls_200_servers
  roles:
    - role: common
    - role: 1_4_efiboot
    - role: 1_5_hwclock
    - role: 1_6_deploy
    - role: 1_7_1_gcc_make
    - role: 1_7_2_nvidia
    - role: 1_7_3_golang
    - role: 2_1_software_install
    - role: 3_1_os_config
    - role: 3_2_docker_ip
    - role: 3_3_exporter
    - role: 3_4_docker_images
    - role: 4_1_filter_tables